---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-jul4-5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-jul4-5 
  name: test-jul4-5
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi